# Generated by Django 3.0.8 on 2021-06-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='upvoters',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='views',
            field=models.TextField(),
        ),
    ]
